import type { Metadata } from "next";
import { ChakraProvider } from "./chakra-provider";
import { Header } from "./components/header";
import { TITLE } from "./constants";

export const metadata: Metadata = {
  title: TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Header />
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
